"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)
from decouple import AutoConfig
config = AutoConfig(search_path=BASE_DIR)

SECRET_KEY = config("DJANGO_SECRET_KEY")
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

DOMAIN = config("DOMAIN", default="localhost")

# Google recaptcha # todo: consider moving these into the wagtail_advanced_form_builder directory
RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY", default=None)
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY", default=None)

STAGING = config("STAGING", default=False, cast=bool)
PRODUCTION = config("PRODUCTION", default=False, cast=bool)


# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = f'https://{DOMAIN}'


ALLOWED_HOSTS = [DOMAIN]
# INTERNAL_IPS = ['127.0.0.1']
CSRF_TRUSTED_ORIGINS = [WAGTAILADMIN_BASE_URL]

SITE_ID = 1

WAGTAIL_ENABLE_UPDATE_CHECK = 'lts'


# Application definition

INSTALLED_APPS = [
    'base',
    'search',

    'wagtail_advanced_form_builder',
    'django_htmx',
    # 'captcha',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',

    'wagtail.contrib.settings',
    'wagtail_modeladmin',

    'wagtail_link_block',
    'modelcluster',
    'taggit',
    'structured_data',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.postgres',

    # enable wagtail style guide (eg to see available icons)
    'wagtail.contrib.styleguide',

    # # enable django-debug-toolbar:
    # 'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # # enable django-debug-toolbar:
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
                'project.context_processors.debug',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# https://pypi.org/project/dj-database-url/
# .parse instead of .config so we can use python-decouple to ensures the connection string is recognised on Windows.
import dj_database_url
DATABASES = {}
DATABASES["default"] = dj_database_url.parse(config("DATABASE_URL"), conn_max_age=5000)


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            # UserAttributeSimilarityValidator uses gestalt pattern matching to determine how similar the user attributes look to the password on a scale of 0-1.
            # The default is 0.7 similarity but this somehow allows the full name to be in the password so I've decreased this to 0.4.
            'max_similarity': 0.4,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-nz'

TIME_ZONE = 'UTC'

USE_I18N = True


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AWS_S3_FILE_OVERWRITE = False

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT = config("EMAIL_PORT", default=1025)
EMAIL_HOST = config("EMAIL_HOST", default="localhost")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default=None)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=None)
FORM_SUBMISSION_EMAIL = config("FORM_SUBMISSION_EMAIL", default=None)
EMAIL_USE_TLS = True

# Wagtail settings

WAGTAIL_SITE_NAME = "project"

WAGTAILEMBEDS_RESPONSIVE_HTML = True

WAGTAILIMAGES_IMAGE_MODEL = 'base.CustomImage'

WAGTAILDOCS_DOCUMENT_MODEL = 'base.CustomDocument'

WAGTAIL_USAGE_COUNT_ENABLED = True

AUTH_USER_MODEL = 'base.User'

WAGTAILUSERS_PASSWORD_REQUIRED = False

# WAGTAILADMIN_NOTIFICATION_USE_HTML = True # uncomment if sending HTML emails

# Search
# https://docs.wagtail.io/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.database',
        "SEARCH_CONFIG": "english",
    }
}

# Logging # todo: see if we should be storing these logs
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}
