# Generated by Django 6.0.7 on 2026-07-10 09:04

import django.db.models.deletion
import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_articleindexpage_articlepage_homepage_standardpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_links', wagtail.fields.StreamField([('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_to', 1), ('page', 2), ('file', 3), ('custom_url', 4), ('anchor', 5), ('email', 6), ('phone', 7), ('new_window', 8)]], {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: You can add the name or ID of section which should be scrolled to (must match a section name used by the Section Identifier Block).', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 9), ('section_id', 10)]], {})})),
                ('show_search_in_nav', models.BooleanField(default=False, help_text='Add the search page to the list of nav items')),
                ('footer_column_1_heading', models.CharField(blank=True, max_length=40, null=True)),
                ('footer_column_1', wagtail.fields.StreamField([('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_to', 1), ('page', 2), ('file', 3), ('custom_url', 4), ('anchor', 5), ('email', 6), ('phone', 7), ('new_window', 8)]], {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: You can add the name or ID of section which should be scrolled to (must match a section name used by the Section Identifier Block).', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 9), ('section_id', 10)]], {})}, default='')),
                ('footer_column_2_heading', models.CharField(blank=True, max_length=40, null=True)),
                ('footer_column_2', wagtail.fields.StreamField([('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_to', 1), ('page', 2), ('file', 3), ('custom_url', 4), ('anchor', 5), ('email', 6), ('phone', 7), ('new_window', 8)]], {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: You can add the name or ID of section which should be scrolled to (must match a section name used by the Section Identifier Block).', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 9), ('section_id', 10)]], {})}, default='')),
                ('footer_column_3_heading', models.CharField(blank=True, max_length=40, null=True)),
                ('footer_column_3', wagtail.fields.StreamField([('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_to', 1), ('page', 2), ('file', 3), ('custom_url', 4), ('anchor', 5), ('email', 6), ('phone', 7), ('new_window', 8)]], {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: You can add the name or ID of section which should be scrolled to (must match a section name used by the Section Identifier Block).', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 9), ('section_id', 10)]], {})}, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_site_description', models.CharField(help_text='Used by search engines when there is not a specific description for the page. Should be between 50 and 160 characters (any longer and the text may be truncated by many search engines.', max_length=160, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_social_media', models.BooleanField(default=False, help_text='Enable this to show social media icons in the footer.')),
                ('linkedin', models.URLField(blank=True, help_text='Enter the full URL of the page.', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Enter the full URL of the page.', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Enter the full URL of the page.', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter the full URL of the page.', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Enter the full URL of the page.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_article_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customimage')),
                ('navbar_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
